"""Generate GitHub-readable markdown tables from data.py.

Narrative documents are hand-written; these files are fully generated and
carry a header saying so.
"""
from pathlib import Path

import data

ROOT = Path(__file__).resolve().parent.parent
GEN = "<!-- GENERATED by tools/build_markdown.py from tools/data.py - do not edit by hand -->\n\n"
BADGE = {"Low": "🟢 Low", "Medium": "🟡 Medium", "High": "🟠 High", "Critical": "🔴 Critical"}


def table(headers, rows):
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c).replace("|", "/").replace("\n", " ") for c in r) + " |")
    return "\n".join(out) + "\n"


def write(rel, text):
    p = ROOT / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(GEN + text, encoding="utf-8")
    print("wrote", rel)


def asset_inventory():
    text = "# Asset inventory\n\nCriticality reflects the consequence to safety, production and quality if the asset's integrity or availability is lost.\n\n"
    text += table(["ID", "Asset", "Zone", "Purdue", "Criticality", "Function", "Security concern", "Threats"],
                  [[a["id"], a["name"], a["zone"], a["purdue"], a["criticality"], a["function"], a["concern"],
                    ", ".join(t["id"] for t in data.THREATS if a["id"] in t["assets"]) or "-"] for a in data.ASSETS])
    text += "\n## Zones\n\n" + table(["Zone", "Name", "Purdue", "SL-T*", "SL-A*", "Contents"],
                                     [[z["id"], z["name"], z["purdue"], z["sl_t"], z["sl_a"], z["desc"]] for z in data.ZONES])
    text += "\n\\* Indicative target / achieved security levels in the spirit of IEC 62443-3-2. They are an assessor's estimate, not a formal SL determination.\n"
    write("architecture/asset-inventory.md", text)


def data_flows():
    text = "# Data flows\n\nNumbered flows used by the DFD ([diagram](../diagrams/data-flow-diagram.png)) and the STRIDE register.\n\n"
    text += table(["ID", "Source", "Destination", "Protocol", "Trust boundary", "Description", "Threats"],
                  [[f["id"], f["src"], f["dst"], f["proto"], f["tb"], f["desc"],
                    ", ".join(t["id"] for t in data.THREATS if f["id"] in t["flows"]) or "-"] for f in data.DATA_FLOWS])
    text += "\n## Trust boundaries\n\n" + table(["ID", "Between", "Enforced by", "State", "Observation"],
                                                [[t["id"], t["between"], t["enforced_by"], t["state"], t["observation"]]
                                                 for t in data.TRUST_BOUNDARIES])
    write("architecture/data-flows.md", text)


def threat_register():
    ts = data.enriched_threats()
    text = "# STRIDE threat register\n\n30 threats derived from the [DFD](../diagrams/data-flow-diagram.png) using STRIDE-per-element. " \
           "Full spreadsheet: [stride-analysis.xlsx](stride-analysis.xlsx). Scoring method: [risk-methodology.md](../risk-assessment/risk-methodology.md).\n\n"
    text += "## Summary\n\n" + table(
        ["ID", "Component / flow", "STRIDE", "Threat", "L", "I", "Risk", "Residual"],
        [[t["id"], ", ".join(t["flows"]), t["stride_name"], t["title"], t["L"], t["I"],
          f"{t['score']} {BADGE[t['rating']]}", f"{t['rscore']} {BADGE[t['rrating']]}"] for t in ts])
    text += "\n## Detail\n"
    for t in ts:
        text += f"""
### {t['id']} - {t['title']}

| Field | Value |
|---|---|
| STRIDE | {t['stride_name']} |
| Assets | {', '.join(f"{a} {data.asset_name(a)}" for a in t['assets'])} |
| Data flows | {', '.join(t['flows'])} |
| Threat | {t['desc']} |
| Threat actor | {', '.join(f"{a} {data.ACTORS[a]}" for a in t['actor'].split(', '))} |
| Attack path | {t['path']} |
| Existing controls | {t['existing']} |
| Likelihood x Impact | {t['L']} x {t['I']} = **{t['score']} {t['rating']}** |
| Recommended mitigation | {'; '.join(f"{c} {data.control(c)['name']}" for c in t['controls'])} |
| Residual | {t['rL']} x {t['rI']} = **{t['rscore']} {t['rrating']}** |
| Attack scenarios | {', '.join(t['scenarios']) or '-'} |
"""
    write("threat-model/stride-threat-register.md", text)


def top_risks():
    text = "# Top 10 risks\n\nRanking rule: score, then impact, then number of attack scenarios the threat enables, then ID.\n\n"
    text += table(["Rank", "ID", "Risk", "STRIDE", "Score", "Scenarios", "Priority controls", "Residual"],
                  [[k, t["id"], t["title"], t["stride_name"], f"{t['score']} {BADGE[t['rating']]}",
                    ", ".join(t["scenarios"]) or "-", ", ".join(t["controls"]),
                    f"{t['rscore']} {BADGE[t['rrating']]}"] for k, t in enumerate(data.top_risks(), 1)])
    ts = data.enriched_threats()
    text += "\n## Distribution\n\n" + table(["Rating", "Current", "Residual"],
                                            [[BADGE[r], sum(t["rating"] == r for t in ts), sum(t["rrating"] == r for t in ts)]
                                             for r in ["Critical", "High", "Medium", "Low"]])
    text += "\n![Risk matrix](risk-matrix.png)\n"
    write("risk-assessment/top-risks.md", text)


def framework_mapping():
    text = ("# Control-to-framework mapping\n\n"
            "IEC 62443 references are IEC 62443-3-3 system requirements (SR) unless another part is named. "
            "NIST references are SP 800-53 Rev. 5 controls as tailored by the SP 800-82 Rev. 3 OT overlay. "
            "CSF references are NIST Cybersecurity Framework 2.0 categories/subcategories.\n\n")
    text += table(["Control", "Name", "IEC 62443", "NIST SP 800-53 / 800-82r3", "NIST CSF 2.0", "Mitigates"],
                  [[c["id"], c["name"], c["iec"], c["nist"], c["csf"], ", ".join(data.threats_for_control(c["id"]))]
                   for c in data.CONTROLS])
    write("controls/framework-mapping.md", text)


def roadmap():
    text = "# Remediation roadmap\n\n"
    for h in ["0-30 days", "30-90 days", "3-12 months"]:
        items = [r for r in data.ROADMAP if r["horizon"] == h]
        text += f"\n## {h}\n\n" + table(
            ["ID", "Action", "Controls", "Threats addressed", "Owner", "Effort"],
            [[r["id"], r["action"], ", ".join(r["controls"]),
              ", ".join(sorted({t for c in r["controls"] for t in data.threats_for_control(c)})),
              r["owner"], r["effort"]] for r in items])
    write("controls/remediation-roadmap.md", text)


if __name__ == "__main__":
    data.validate()
    asset_inventory()
    data_flows()
    threat_register()
    top_risks()
    framework_mapping()
    roadmap()
